# EXPLANATION: configmap to hold service names for the various containers
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  mongodb-hostname: mongodb-service
  transcription-api-hostname: transcription-service
