# EXPLANATION: secrets are base64 encoded. I attempted setting this via user-input shell commands without much luck!
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==
  mongo-root-password: c2VjcmV0
