# EXPLANATION: Main deployment and service for the model
#              Requires being exposed outside of the cluster to allow user interaction
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcription-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcription-pod
  template:
    metadata:
      labels:
        app: transcription-pod
    spec:
      containers:
        - name: diabolocom-ai
          # EXPLANATION: this is an image I've pushed-up to my Github Packages and is available publicly
          image: ghcr.io/abdulqadirq/diabolocom-ai:latest
          ports:
            - containerPort: 8000
          env:
            # EXPLANATION: a configmap is used to find the mongodb service for the statistics
            - name: MONGO_INITDB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: mongodb-hostname
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password

---
apiVersion: v1
kind: Service
metadata:
  name: transcription-service
spec:
  selector:
    app: transcription-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # EXPLANATION: this port may be better set within a config file. It may likely conflict with other services on a cluster
      nodePort: 30001
